url: http://ypcs.fi
cdn: http://cdn.ypcs.fi

title: Ville Korhonen (ypcs.fi)
description: Tulevaisuuden visioita Hankasalmelle
language: fi
theme: media/css/kuntavaalit-1.0.2.css

author: Ville Korhonen
email: ville@xd.fi


markdown: rdiscount
pygments: true
exclude: ['README.md']
permalink: pretty

# Username(s) for misc services
github: ypcs
flattr: ypcs
twitter: ypcs
facebook: ypoocs
feedburner: ypcs
lastfm: ypcs
skype: ypoocs