markdown: rdiscount
pygments: true
exclude: ['README.md']
permalink: pretty
site_url: http://ypcs.fi
site_title: Ville Korhonen
site_tagline: Tulevaisuuden visioita Hankasalmelle
site_author: Ville Korhonen
site_author_email: ville@xd.fi
cdn_url: http://cdn.ypcs.fi
