url: http://ypcs.fi
cdn: http://cdn.ypcs.fi

title: Ville Korhonen (ypcs.fi)
description: Tulevaisuuden visioita Hankasalmelle
language: fi
theme: kuntavaalit2012
style_version: 5ea76ff2
scripts_version: 79bcb60e

author: Ville Korhonen
email: ville@xd.fi


markdown: rdiscount
pygments: true
exclude:
    - README.md
    - requirements.txt

permalink: pretty

# Username(s) for misc services
github: ypcs
flattr: ypcs
twitter: ypcs
facebook: ypoocs
feedburner: ypcs
lastfm: ypcs
skype: ypoocs
