url: http://ypcs.fi
cdn: http://cdn.ypcs.fi
#secure_cdn: https://d3i43hipit3ske.cloudfront.net
#cdn: https://d3i43hipit3ske.cloudfront.net

title: Ville Korhonen (ypcs.fi)
description: Tulevaisuuden visioita Hankasalmelle - numerolla 69
language: fi
theme: kuntavaalit2012

style_version: 2db423f3
scripts_version: feb65480

author: Ville Korhonen
email: ville@xd.fi

markdown: rdiscount
pygments: true
exclude:
    - README.md
    - requirements.txt

permalink: pretty

# Username(s) for misc services
github: ypcs
flattr: ypcs
twitter: ypcs
facebook: ypoocs
feedburner: ypcs
lastfm: ypcs
skype: ypoocs

google_api_key: AIzaSyCHoFj29ohnnuctk1KaDHdMCMuM5NB9Pcw
maps_zoom: 13
maps_size: 200x200
maps_type: roadmap
maps_sensor: false

coverphoto: s3/2012/kunnallisvaalit/coverphoto.png
