url: http://ypcs.fi
cdn: http://cdn.ypcs.fi

title: Ville Korhonen (ypcs.fi)
description:

options:
    language:   fi
    theme:      default
    elements:
        description:    true
        social:         true
        menu:           true

media:
    -   style_version:     xxx
    -   script_version:    yyy
    -   ogimage: http://cdn.ypcs.fi/static/img/ogimage.png

author:
    name:   Ville Korhonen
    email:  ville@xd.fi
    url:    http://ypcs.fi/
    phone:  00358503032101
    photo:  http://cdn.ypcs.fi/static/img/me.jpg

markdown: rdiscount
pygments: true
exclude:
    - README.md
    - requirements.txt

permalink: pretty

accounts:
    github: ypcs
    twitter:    ypcs
    facebook:   ypoocs
    facebookapp: 479137325447561
    skype:  ypoocs
    flattr: ypcs
    feedburner: ypcs
    lastfm: ypcs
    analytics: UA-420043-25
    bitcoin: 1EyXKGMqvbSFo1Dzw9Ci75YHQ3Qr96nB5m
    googleplus: 102939930956749261004
    irc: ypcs
    msvalidate: 8A0446C947E384F2BE52ED4F0397D93E
    # -   service: googleapi
    #     -   key: AIzaSyCHoFj29ohnnuctk1KaDHdMCMuM5NB9Pcw
    #     -   maps:   
    #         zoom:   13
    #         size:   200x200
    #         type:   roadmap
    #         sensor: false

urls:
    contact:    /yhteystiedot/
    home:   /
    license: http://creativecommons.org/licenses/by-sa/3.0/
