url: http://ypcs.fi
cdn: http://cdn.ypcs.fi

title: Ville Korhonen (ypcs.fi)
description: Tulevaisuuden visioita Hankasalmelle
language: fi

author: Ville Korhonen
email: ville@xd.fi


markdown: rdiscount
pygments: true
exclude: ['README.md']
permalink: pretty

